dir:
  persistentVolumeClaim: ""
workDir:
  create: false
name:
  persistentVolume: ""
  persistentVolumeClaim: ""
metastore:
  rolesCreate: false
  databaseHost: hive-postgresql
  databaseName: hive3mr3
  warehouseDir: s3a://
  dbType: postgres
  mountLib: false
  resources:
    requests:
      cpu: 2
      memory: 1Gi
    limits:
      cpu: 2
      memory: 1Gi
  heapSize: 1000
  initSchema: true

create:
  hive: false
hive:
  rolesCreate: false
  port: 9852
  httpport: 10001
  scratchdir: s3a://
  cachedir: s3a://
  resources:
    requests:
      cpu: 2
      memory: 1Gi
    limits:
      cpu: 2
      memory: 1Gi
  heapSize: 1000

docker:
  image: mr3project/hive3:1.9
  containerWorkerImage: mr3project/hive3:1.9

postgresql:
  postgresPassword: abc
  postgresUser: user
  enabled: true
  global:
    postgresql:
      auth:
        username: user
        password: abc
        database: hive3mr3